import os
from dotenv import load_dotenv

load_dotenv()

ENV_APP_NAME = os.getenv("ENV_APP_NAME")
ENV_MASTER_URL = os.getenv("ENV_MASTER_URL")
ENV_HADOOP_USER = os.getenv("ENV_HADOOP_USER")
ENV_TIMEZONE = os.getenv("ENV_TIMEZONE")
ENV_ALLOW_SCHEMA_OVERWRITE = str(os.getenv("ENV_ALLOW_SCHEMA_OVERWRITE")).lower()

ENV_REPARTITION_SIZE = int(os.getenv("ENV_REPARTITION_SIZE"))

ENV_SPARK_CHECKPOINT_DIR = os.getenv("ENV_SPARK_CHECKPOINT_DIR")

ENV_SPARK_EXECUTORS_MEMORY = os.getenv("ENV_SPARK_EXECUTORS_MEMORY", "2g")
ENV_SPARK_EXECUTORS_CORES = os.getenv("ENV_SPARK_EXECUTORS_CORES", "2")
ENV_SPARK_EXECUTORS_OVERHEAD = os.getenv("ENV_SPARK_EXECUTORS_OVERHEAD", "1g")
ENV_SPARK_NETWORK_TIMEOUT = os.getenv("ENV_SPARK_NETWORK_TIMEOUT", "600s")
ENV_SPARK_SHUFFLE_MAX_RETRIES = os.getenv("ENV_SPARK_SHUFFLE_MAX_RETRIES", "10")
ENV_SPARK_SHUFFLE_RETRY_WAIT = os.getenv("ENV_SPARK_SHUFFLE_RETRY_WAIT", "5s")
ENV_SPARK_SHUFFLE_PARTITIONS = int(os.getenv("ENV_SPARK_SHUFFLE_PARTITIONS", 96))
ENV_SPARK_PARTITITION_SIZE = os.getenv("ENV_SPARK_PARTITITION_SIZE", "64m")
ENV_SPARK_ADAPTIVE_ENABLED = os.getenv("ENV_SPARK_ADAPTIVE_ENABLED", "true")
ENV_SPARK_SKEW_JOIN_ENABLED = os.getenv("ENV_SPARK_SKEW_JOIN_ENABLED", "true")
ENV_SPARK_COALESCE_PARTITIONS_ENABLED = os.getenv("ENV_SPARK_COALESCE_PARTITIONS_ENABLED", "true")

ENV_SAVE_TO_PGSQL_TRUNCATE = os.getenv("ENV_SAVE_TO_PGSQL_TRUNCATE", "true")
ENV_SAVE_TO_PGSQL_BATCHSIZE = os.getenv("ENV_SAVE_TO_PGSQL_BATCHSIZE", "200")


ENV_SOURCE_PQ_URL = os.getenv("ENV_SOURCE_PQ_URL")
ENV_SOURCE_PQ_USER = os.getenv("ENV_SOURCE_PQ_USER")
ENV_SOURCE_PQ_PASSWORD = os.getenv("ENV_SOURCE_PQ_PASSWORD")
ENV_SOURCE_PQ_SCHEMA_TABLE = os.getenv("ENV_SOURCE_PQ_SCHEMA_TABLE")
ENV_SOURCE_PQ_DRIVER = os.getenv("ENV_SOURCE_PQ_DRIVER")

ENV_SOURCE_TABLE = os.getenv("ENV_SOURCE_TABLE")
ENV_SOURCE_FETCH_SIZE = os.getenv("ENV_SOURCE_FETCH_SIZE")

ENV_SINK_HOST = os.getenv("ENV_SINK_HOST")
ENV_SINK_PORT = os.getenv("ENV_SINK_PORT")
ENV_SINK_DB = os.getenv("ENV_SINK_DB")
ENV_SINK_REWRITE_BATCHED_INSERTS = os.getenv("ENV_SINK_REWRITE_BATCHED_INSERTS")

ENV_SINK_PQ_URL = "jdbc:postgresql://{host}:{port}/{database}".format(
    host=ENV_SINK_HOST,
    port=ENV_SINK_PORT,
    database=ENV_SINK_DB
)

ENV_SINK_PQ_USER = os.getenv("ENV_SINK_PQ_USER")
ENV_SINK_PQ_PASSWORD = os.getenv("ENV_SINK_PQ_PASSWORD")
ENV_SINK_PQ_DRIVER = os.getenv("ENV_SINK_PQ_DRIVER")
ENV_SINK_ENTITY_REGISTRY = os.getenv("ENV_SINK_ENTITY_REGISTRY")


ENV_DELTA_BRONZE_RAW_DATA = os.getenv("ENV_DELTA_BRONZE_RAW_DATA")

ENV_DELTA_GOLD_STAGING = os.getenv("ENV_DELTA_GOLD_STAGING")

ENV_DELTA_SILVER_FOLDER = os.getenv("ENV_DELTA_SILVER_FOLDER")
ENV_DELTA_SILVER_REGISTRY = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_REGISTRY")

ENV_DELTA_SILVER_HISTORY_NAMES = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_NAMES")
ENV_DELTA_SILVER_COMPANY_CURRENT = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_COMPANY_CURRENT")

ENV_DELTA_SILVER_HISTORY_IDENTIFIERS = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_IDENTIFIERS")
ENV_DELTA_SILVER_HISTORY_LEGAL_FORM = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_LEGAL_FORM")
ENV_DELTA_SILVER_HISTORY_HAS_OPP_STATUS = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_HAS_OPP_STATUS")
ENV_DELTA_SILVER_HISTORY_BUSINESS_WITH_OTHERS = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_BUSINESS_WITH_OTHERS")

ENV_DELTA_SILVER_HISTORY_ADDRESS = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_ADDRESS")
ENV_DELTA_SILVER_HISTORY_HEADQUARTERS = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_HEADQUARTERS")
ENV_DELTA_SILVER_HISTORY_WEBPAGE = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_WEBPAGE")
ENV_DELTA_SILVER_HISTORY_EMAIL = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_EMAIL")
ENV_DELTA_SILVER_HISTORY_ELECTRONIC_BAE_DELIVERY = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_ELECTRONIC_BAE_DELIVERY")
ENV_DELTA_SILVER_HISTORY_MAIN_HQ_ADDRESS = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_MAIN_HQ_ADDRESS")

ENV_DELTA_SILVER_HISTORY_TIME_ENTITY_CREATED = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_TIME_ENTITY_CREATED")
ENV_DELTA_SILVER_HISTORY_STATUTE_CHANGE = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_STATUTE_CHANGE")

ENV_DELTA_SILVER_HISTORY_SHARE_CAPITAL_AMOUNT = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_SHARE_CAPITAL_AMOUNT")
ENV_DELTA_SILVER_HISTORY_TOTAL_SHARES_UNITS = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_TOTAL_SHARES_UNITS")
ENV_DELTA_SILVER_HISTORY_SINGLE_SHARE_VALUE = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_SINGLE_SHARE_VALUE")
ENV_DELTA_SILVER_HISTORY_PAID_IN_CAPITAL_PART = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_PAID_IN_CAPITAL_PART")

ENV_DELTA_SILVER_HISTORY_SHARE_ISSUES_SERIES_NAME = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_SHARE_ISSUES_SERIES_NAME")
ENV_DELTA_SILVER_HISTORY_SHARE_ISSUES_SHARES_IN_SERIES = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_SHARE_ISSUES_SHARES_IN_SERIES")
ENV_DELTA_SILVER_HISTORY_SHARE_ISSUES_PREFERENCE_INFO = ENV_DELTA_SILVER_FOLDER + os.getenv("ENV_DELTA_SILVER_HISTORY_SHARE_ISSUES_PREFERENCE_INFO")